reviews/posts/routes.py
import os
from flask import render_template, url_for, redirect, Blueprint
from flask_login import current_user, login_required
from reviews import app, db
from reviews.models import Restaurant, User, DishType, Dish, Post
from reviews.posts.forms import post_reviews_form, edit_post_form
from reviews.posts.helper import (
    valid_phone_number, get_dish_overview, directory_exists,
    transform_name, image_resizer, get_my_post, image_adder
)

posts = Blueprint('posts', __name__)

# Posts Review
@posts.route('/post_review', methods=['GET', 'POST'])
@login_required
def post_review(): 
    if (current_user.role == 'restaurant' or current_user.role == 'admin'):
        return redirect(url_for('main.home'))
    form = post_reviews_form()
    if form.validate_on_submit():
        with app.app_context(): 
            restaurant = Restaurant.query.filter_by(name=form.restaurant.data, address=form.restaurant_address.data).first()
            if restaurant is None: 
                user = User.query.filter_by(username=current_user.username).first()
                city = user.location
                phone_number = valid_phone_number(form.phone_number.data, city)
                restaurant = Restaurant(name=form.restaurant.data, \
                    cuisine=form.restaurant_cuisine.data, address=form.restaurant_address.data,\
                    phone_number=phone_number)
                db.session.add(restaurant)
                db.session.commit()
            dish_type = DishType.query.filter_by(type=form.dish_type.data).first()
            if (dish_type is None): 
                dishtype, overview = get_dish_overview(form.dish_type.data)
                dish_type = DishType(type = dishtype, overview=overview)
                db.session.add(dish_type)
                db.session.commit()
            dish = Dish.query.filter_by(name=form.dish.data).first()
            if dish is None: 
                dish = Dish(name=form.dish.data, dishtype=dish_type)
                db.session.add(dish)
                db.session.commit()
            post = Post(title=form.title.data, restaurant_rating=form.restaurant_rating.data,\
                    value=form.value.data, size=form.dish_size.data, dish_rating=form.dish_rating.data, cost=form.dish_cost.data,\
                    content=form.content.data, user=current_user, restaurant=restaurant, dish=dish)
            db.session.add(post)
            db.session.commit()
            directory_exists("post", post.id)
            path = f"C:/Users/Gordon Li/Desktop/restaurant_reviews/reviews/static/post/{post.id}"
            file_restaurant = form.restaurant_image.data
            file_dish = form.dish_image.data
            if file_restaurant: 
                new_filename = transform_name('restaurant', file_restaurant.filename)  
                file_restaurant.save(os.path.join(path, new_filename))
                image_resizer(os.path.join(path, new_filename))
            if file_dish: 
                new_filename = transform_name('dish', file_dish.filename)  
                file_dish.save(os.path.join(path, new_filename))
                image_resizer(os.path.join(path, new_filename))
        return redirect(url_for('users.account_info'))
    return render_template('post.html', form=form)

# Get Started on posting
@posts.route('/post_review/get_started')
@login_required
def get_started(): 
    return render_template('get_started.html')

# Edit Post
@posts.route('/edit_post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def edit_posts_by_id(post_id):
    post = Post.query.get_or_404(post_id)
    if (post.user_id != current_user.id): 
        return redirect(url_for('main.home'))
    new_list = get_my_post(post_id)
    post_list = image_adder(new_list, 'my_post', current_user.id)
    form = edit_post_form()
    if form.validate_on_submit(): 
        post = Post.query.filter_by(id=post_id).first() 
        if (form.title.data != ''): 
            post.title = form.title.data
        post.restaurant_rating = form.restaurant_rating.data
        post.dish_rating = form.dish_rating.data
        post.cost = form.dish_cost.data
        post.size = form.dish_size.data
        post.value = form.value.data
        if form.content.data != '':
            post.content = form.content.data
        db.session.commit()
        return redirect(url_for('post.edit_posts_by_id', post_id=post_id))
    return render_template('edit_post.html', user_id=current_user.id, review=post_list[0], form=form)

reviews/privileges/routes.py
from flask import render_template, url_for, redirect, flash, Blueprint
from flask_login import current_user, login_required
from reviews import db, app
from reviews.models import User, Post, Feedback, RestaurantUser
from reviews.privileges.forms import my_posts_form
from reviews.privileges.helper import (
    get_user_profile, get_user_posts, image_adder, user_dashboard_info
)

privileges = Blueprint('privileges', __name__)

#Gets user profile
@privileges.route('/user')
@login_required
def user(): 
    profile_settings = get_user_profile()
    return render_template('user_db.html', profile_settings=profile_settings)


@privileges.route('/user/<int:user_id>')
def user_profile(user_id): 
    if (user_id == current_user.id):
        return redirect(url_for('users.account_info'))
    user = User.query.filter_by(id=user_id).first()
    return render_template('user.html', user=user)

# Get User Posts
@privileges.route('/user/<int:user_id>/reviews', methods=['GET', 'POST'])
def user_posts(user_id): 
    if (user_id == current_user.id): 
        return redirect(url_for('users.account_posts'))
    user = User.query.filter_by(id=user_id).first()
    form = my_posts_form()
    new_list = get_user_posts(user_id, '')
    post_list = image_adder(new_list, 'account', user_id)
    if form.validate_on_submit(): 
        if form.search.data != '':
            string = f"and p.id=\'{form.search.data}\'"
        else:
            string = ''
        new_list = get_user_posts(user_id, string)
        post_list = image_adder(new_list, 'account', user_id)
    return render_template('account_posts.html', form=form, post_list=post_list, owner=False, user=user, user_id=user_id)

# Gets User Dashboard
@privileges.route('/user/<int:user_id>/dashboard')
def user_dashboard(user_id): 
    user = User.query.get_or_404(user_id)
    if (current_user.id == user_id): 
        return redirect(url_for('users.account_dashboard'))
    with app.app_context(): 
        posts = Post.query.filter_by(user_id=user_id).all()
        if (len(posts) == 0): 
            flash("Dashboard doesn't exist as user hasn't made a post yet", 'danger')
            return redirect(url_for('privileges.user_profile', user_id=user_id))
    username = user.username
    count_wk, count_month, count_half_yr, count_yr, avg_restaurant, avg_dish,\
        cuisine_labels, cuisine_values, cost_labels, cost_values,\
        restaurant_labels, restaurant_values, dish_labels, dish_values,\
        popular_labels, popular_values, top_3_dish_labels, top_3_dish_values = user_dashboard_info(user_id)
    colours = ['#F9F9F9', '#E072A4', '#6883BA', '#3D3B8E', '#B0E298']
    popular_colors = colours[:len(popular_values)]
    top_3_dish_colors = colours[:len(top_3_dish_values)]
    avg_rating = (avg_restaurant + avg_dish)/2
    print(restaurant_labels, restaurant_values, dish_labels, dish_values)
    return render_template('account_dashboard.html', username=username,
        count_wk=count_wk, count_month=count_month, count_half_yr=count_half_yr, count_yr=count_yr,
        avg_rating=avg_rating, avg_restaurant=avg_restaurant, avg_dish=avg_dish,
        cuisine_labels=cuisine_labels, cuisine_values=cuisine_values,
        cost_labels=cost_labels, cost_values=cost_values, 
        restaurant_labels=restaurant_labels, restaurant_values=restaurant_values,
        dish_labels=dish_labels, dish_values=dish_values,
        popular_labels=popular_labels, popular_values=popular_values,
        popular_colors=popular_colors,
        top_3_dish_labels=top_3_dish_labels, top_3_dish_values=top_3_dish_values,
        top_3_dish_colors=top_3_dish_colors,
        color=colours)
    
@privileges.route('/notifications/admin', methods=['GET', 'POST'])
def notifications_admin():
    if (current_user.role == 'admin'):
        feedbacks = Feedback.query.all()
        restaurant_users = RestaurantUser.query.filter_by(status="Unsolved").all()
        return render_template('notifications_admin.html', feedbacks=feedbacks,
            restaurant_users=restaurant_users)
    else: 
        return redirect(url_for('main.home'))

reviews/users/routes.py
import os
from flask import (render_template, url_for, flash, redirect, request, Blueprint)
from flask_login import login_user, logout_user, current_user
from reviews import db, app
from reviews.models import User, Post
from reviews.users.forms import (registration_form, login_form, edit_username_form,
    edit_password_form, edit_profile_picture_form, edit_location_form, my_posts_form)
from reviews.users.helper import (directory_exists, transform_name, logo_remover,
                                  notifications_replies, notifications_feedback, notifications_approval
                                  ,image_adder, get_user_posts, user_dashboard_info)

users = Blueprint('users', __name__)

@users.route("/register", methods = ['GET', 'POST'])
def register(): 
    form = registration_form()
    if form.validate_on_submit():
        with app.app_context(): 
            user = User(username=form.username.data, email=form.email.data, location=form.location.data, 
                password=form.password.data)
            db.session.add(user)
            db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login(): 
    if current_user.is_authenticated: 
        return redirect(url_for('users.account_info'))
    form = login_form()
    if form.validate_on_submit():
        with app.app_context():
            user = User.query.filter_by(email=form.email.data).first()
            if (user and user.password == form.password.data): 
                print(user.id)
                if(user.id == 1 and user.role == 'regular'):
                    user.role = 'admin'
                    db.session.commit()
                login_user(user)
                next = request.args.get('next')
                return redirect(next or url_for('users.account_info'))
            else: 
                flash('Cannot Login. Please change your email or password and try again!', 'danger')
    return render_template('login.html', form=form)

# Log User Out
@users.route('/logout')
def logout(): 
    logout_user()
    return redirect(url_for('main.home'))

# Gets Account Info
@users.route('/account_info')
def account_info(): 
    path = f"C:/Users/Gordon Li/Desktop/restaurant_reviews/reviews/static/user/{current_user.id}"
    profile_picture = 'default_user_profile.jpg'
    if (os.path.exists(path)):
        profile_picture = os.listdir(path)[0]
    return render_template('account_info.html', profile_picture=profile_picture)

# Edits account username
@users.route('/edit_username', methods=['GET', 'POST'])
def edit_username(): 
    form = edit_username_form()
    if form.validate_on_submit(): 
        with app.app_context():
            current_user.username = form.username.data
            db.session.commit()
        return redirect(url_for('users.account_info'))
    elif (request.method == 'GET'): 
        form.username.data = current_user.username
    return render_template('edit_username.html', form=form)

# Edits password
@users.route('/edit_password', methods=['GET', 'POST'])
def edit_password(): 
    form = edit_password_form()
    if form.validate_on_submit(): 
        with app.app_context(): 
            current_user.password = form.new_password.data
            db.session.commit() 
        return redirect(url_for('users.account_info'))
    return render_template('edit_password.html', form=form)

# Edits user profile picture
@users.route('/edit_profile_picture', methods=['GET', 'POST'])
def edit_profile_picture(): 
    path = f"C:/Users/Gordon Li/Desktop/restaurant_reviews/reviews/static/user/{current_user.id}"
    profile_picture = None
    if (os.path.exists(path)):
        profile_picture = os.listdir(path)[0]
    form = edit_profile_picture_form()
    if form.validate_on_submit(): 
        path = directory_exists('user', current_user.id)
        file = form.picture.data
        print(file.filename)
        new_filename = transform_name("user_pic", file.filename)
        print(new_filename)
        logo_remover("user_pic.", path)
        file.save(os.path.join(path, new_filename))
        return redirect(url_for('users.account_info'))
    return render_template('edit_profile_pic.html', form=form, profile_picture=profile_picture)

# Edits location user
@users.route('/edit_location', methods=['GET', 'POST'])
def edit_location(): 
    form = edit_location_form()
    if form.validate_on_submit(): 
        with app.app_context(): 
            current_user.location = form.location.data
            db.session.commit() 
        return redirect(url_for('users.account_info'))
    return render_template('edit_location.html', form=form)

# Gets notifications
@users.route('/notifications')
def notifications_regular(): 
    if (current_user.role == 'admin'): 
        return redirect(url_for('notifications_admin'))
    user_id = current_user.id
    notifications_reply = notifications_replies(user_id)
    notifications_feedbacks = notifications_feedback(user_id)
    approvals = notifications_approval(user_id)
    return render_template('notifications_regular.html', replies=notifications_reply, 
                           feedbacks=notifications_feedbacks, approvals=approvals)

# Gets account posts
@users.route('/account_posts', methods=['GET', 'POST'])
def account_posts(): 
    form = my_posts_form()
    new_list = get_user_posts(current_user.id, '')
    post_list = image_adder(new_list, 'account', current_user.id)
    user_id = current_user.id
    if form.validate_on_submit(): 
        if form.search.data != '':
            string = f"and p.id=\'{form.search.data}\'"
        else:
            string = ''
        new_list = get_user_posts(current_user.id, string)
        post_list = image_adder(new_list, 'account', current_user.id)
    print(post_list)
    return render_template('account_posts.html', form=form, post_list=post_list, owner=True, user_id=user_id)

# Get account dashboard
@users.route('/account_dashboard')
def account_dashboard(): 
    username = current_user.username
    user_id = current_user.id
    with app.app_context(): 
        posts = Post.query.filter_by(user_id=user_id).all()
        if (len(posts) == 0): 
            flash("Dashboard doesn't exist as user hasn't made a post yet", 'danger')
            return redirect(url_for('privileges.user_profile', user_id=user_id))
    count_wk, count_month, count_half_yr, count_yr, avg_restaurant, avg_dish,\
        cuisine_labels, cuisine_values, cost_labels, cost_values,\
        restaurant_labels, restaurant_values, dish_labels, dish_values,\
        popular_labels, popular_values, top_3_dish_labels, top_3_dish_values = user_dashboard_info(user_id)
    colours = ['#F9F9F9', '#E072A4', '#6883BA', '#3D3B8E', '#B0E298']
    popular_colors = colours[:len(popular_values)]
    top_3_dish_colors = colours[:len(top_3_dish_values)]
    avg_rating = (avg_restaurant + avg_dish)/2
    print(popular_colors)
    return render_template('account_dashboard.html', username=username,
        count_wk=count_wk, count_month=count_month, count_half_yr=count_half_yr, count_yr=count_yr,
        avg_rating=avg_rating, avg_restaurant=avg_restaurant, avg_dish=avg_dish,
        cuisine_labels=cuisine_labels, cuisine_values=cuisine_values,
        cost_labels=cost_labels, cost_values=cost_values, 
        restaurant_labels=restaurant_labels, restaurant_values=restaurant_values,
        dish_labels=dish_labels, dish_values=dish_values, 
        popular_labels=popular_labels, popular_values=popular_values,
        popular_colors=popular_colors,
        top_3_dish_labels=top_3_dish_labels, top_3_dish_values=top_3_dish_values,
        top_3_dish_colors=top_3_dish_colors, color=colours)


reviews/templates/account_info.html
{% extends "layout.html" %}
{% block content %}
<div style="background-color:#B83B5E">
    <br></br>
    <br></br>
    <br></br>
    <div class="container p-3 rounded-3" style="background-color:#6A2C70; color:#F9ED69; width: 700px">
        <h1 class="text-center">Account Information</h1>
        <div class="row p-1">
            <div class="col-md-1 m-1 p-2"></div>
            <div class="col md-8 m-1 p-2">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
            <div class="col-md-1 m-1 p-2"></div>
        </div>
        <div class="row p-1">
            <div class="col-md-1 m-1 p-2"></div>
            <div class="col-md-3 m-1 p-2">
                <p style="font-size:22px">Email</p>            
            </div>
            <div class="col-md-5 m-1 p-2">
                <p style="font-size:18px">{{ current_user.email }}</p>
            </div>
        </div>
        <div class="row p-1">
            <div class="col-md-1 m-1 p-2"></div>
            <div class="col-md-3 m-1 p-2">
                <p style="font-size:22px">Username</h6>            
            </div>
            <div class="col-md-5 m-1 p-2">
                <p style="font-size:18px">{{ current_user.username }}</p>
            </div>
            <div class="col-md-2 m-1 p-2">
                <a class="btn btn-info" href="/edit_username" role="button">
                    <i class="bi bi-pen"></i>
                </a> 
            </div>
        </div>  
        <div class="row p-1">
            <div class="col-md-1 m-1 p-2"></div>
            <div class="col-md-3 m-1 p-2">
                <p style="font-size:22px">Password</p>
            </div>
            <div class="col-md-5 m-1 p-2">
                <p style="font-size:18px">{{ current_user.password }}</p>
            </div>
            <div class="col-md-2 m-1 p-2">
                <a class="btn btn-info" href="/edit_password" role="button">
                    <i class="bi bi-pen"></i>
                </a> 
            </div>
        </div> 
        <div class="row p-1">
            <div class="col-md-1 m-1 p-2"></div>
            <div class="col-md-3 m-1 p-2">
                <p style="font-size:22px">Location</p>
            </div>
            <div class="col-md-5 m-1 p-2">
                <p style="font-size:18px">{{ current_user.location }}</p>
            </div>
            <div class="col-md-2 m-1 p-2">
                <a class="btn btn-info" href="/edit_location" role="button">
                    <i class="bi bi-pen"></i>
                </a> 
            </div>
        </div>
        <div class="row p-1 align-items-center">
            <div class="col-md-1 m-1 p-2"></div>
            <div class="col-md-3 m-1 p-2">
                <p style="font-size:22px">Profile Picture</h6>
            </div>
            <div class="col-md-5 m-1 p-2">
                <p style="font-size:18px">{{ profile_picture }}</p>
            </div>
            <div class="col-md-2 m-1 p-2">
                <a class="btn btn-info" href="{{ url_for('users.edit_profile_picture')}}" role="button">
                    <i class="bi bi-pen"></i>
                </a> 
            </div>
        </div>
        <div class="row p-1 align-items-center">
            <div class="col-md-1 m-1 p-2"></div>
            <div class="col-md-3 m-1 p-2">
                <p style="font-size:22px">Role</h6>
            </div>
            <div class="col-md-5 m-1 p-2">
                <p style="font-size:18px">{{ current_user.role }}</p>
            </div>
            {% if current_user.role == 'regular' %}
                <div class="col-md-2 m-1 p-2">
                    <a class="btn btn-info" href=" {{ url_for('applications.restaurant_app' )}}" role="button">
                        <i class="bi bi-pen"></i>
                    </a> 
                </div>
            {% endif %}
        </div>
        <br></br>
        <div class="row p-1">
            <div class="col-2"></div>
        </div>
        <div class="row p-1">
            <div class="col-2"></div>
            <div class="col-3">
                <a class="btn btn-primary" href="{{ url_for('users.account_posts') }}" role="button">Posts</a>
            </div>
            <div class="col-2"></div>
            <div class="col-3">
                <a class="btn btn-primary" href="{{ url_for('users.account_dashboard') }}" role="button">Dashboard</a>
            </div>
        </div>
    </div>
    <br></br>
    <br></br>
    <br></br>
</div>
{% endblock content %}

reviews/templates/account_posts.html
{% extends "layout.html" %}
{% block content %}
<div style="background-color:#B83B5E; color:#F9ED69">
    <div class="container p-3">
        <div class="row p-1 text-center">
            {% if owner %}
                <h1>My Posts</h1>
            {% else %}
                <h1>Posts for {{ user.username}}</h1>
            {% endif %}
        </div>
        <br></br>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="row p-1">
                <div class="col-3"></div>
                <div class="col-4">
                </div>
                <div class="col-4">
                    <div class="form-floating">
                        {% if form.search.errors %}
                            {{ form.search(class="form-control form-control-lg is-invalid") }}  
                            <div class="invalid-feedback">
                                {% for error in form.search.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.search(class="form-control form-control-lg") }}
                        {% endif %}
                        {{ form.search.label(class="form-control-label") }}
                    </div>
                </div>
                <div class="col-1">
                    {{ form.submit(class="btn btn-primary")}}
                </div>
            </div>
        </form>
    </div>
</div>
<div style="background-color:#6A2C70; color:#F9ED69; min-height:650px">
    <div class="container mb-3 p-3">
        {% if post_list|length < 1 %}
            <br></br>
            <br></br>
            <br></br>
            <div class="text-center">
                {% if owner %}
                    <em style="font-size: 18px;">You haven't made any posts yet.</em>
                {% else %}
                    <em style="font-size: 18px;">{{ user.username}} hasn't made any posts yet.</em>
                {% endif %}
            </div>
        {% else %}
            {% for posts in post_list %}
                <div class="container rounded-4 p-3">
                    <p style="font-size:22px">Review {{ loop.index }}</p>
                    <div class="d-flex">
                        <div class="flex-shrink-0 p-1">
                            {% if posts[-4] %}
                                <img src="{{ url_for('static', filename="user")}}/{{ user_id }}/{{ posts[-4]}}" style="width:110px; height:145px">
                            {% else %}
                                <img src="{{ url_for('static', filename="default_user_profile.jpg")}}" style="width:110px; height:145px">
                            {% endif %}
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <div class="row p-1">
                                <h5> {{posts[2]}} <small class="text-muted"><i style="color:#F08A5D">Posted on {{ posts[7].strftime("%Y-%m-%d") }}</i></small></h5>
                            </div>
                            <div class="row p-1">
                                <p style="font-size:18px"><a href="{{ url_for('restaurants.restaurant', restaurant_id=posts[0]) }}" style="text-decoration:none; color:#F9ED69">{{ posts[1] }}</a></p>
                            </div>
                            <div class="row p-1">
                                <p style="font-size:18px">{{ posts[8] }} | {{ posts[11] }} | ${{ posts[5] }}</p>
                            </div>
                            <div class="row p-1">
                                <p style="font-size:18px"><strong>Restaurant Rating</strong>: {{ posts[3] }}/5 | <strong>Dish Rating</strong>: {{ posts[4] }} | <strong>Value for money</strong>: {{ posts[10] }}</strong></p>
                            </div>
                            <div class="row p-1">
                                <p style="font-size:18px"><strong>Upvotes</strong>: {{ posts[12] }}</p>
                            </div>
                            <div class="row p-1">
                                <p style="font-size:18px">{{ posts[6] }}</p>
                            </div>
                            <div class="row p-1">
                                {% if posts[-2] %}
                                    <div class="col-3">
                                        <a href="{{ url_for('static', filename='post')}}/{{ posts[9] }}/{{ posts[-2] }}" data-toggle="lightbox">
                                            <img src="{{ url_for('static', filename='post')}}/{{ posts[9] }}/{{ posts[-2] }}" width="200" height="150">
                                        </a>
                                    </div>
                                {% endif %}
                                {% if posts[-1] %}
                                    <div class="col-3">
                                        <a href="{{ url_for('static', filename='post')}}/{{ posts[9] }}/{{ posts[-1] }}" data-toggle="lightbox">
                                            <img src="{{ url_for('static', filename='post')}}/{{ posts[9] }}/{{ posts[-1] }}" width="200" height="150">
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                            {% if posts[13] %}
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0 p-1">
                                        {% if posts[-3] %}
                                            <img src="{{ url_for('static', filename="restaurant") }}/{{ posts[0] }}/{{ posts[-3] }}" width="100" height="100">
                                        {% endif %}
                                    </div>
                                    <div class="flex-grow-1 ms-3">
                                        <div class="row p-1">
                                            <h5>Response from the restaurant <small class="text-muted"><i style="color:#F08A5D">Posted on {{ posts[14].strftime("%Y-%m-%d") }}</i></small></h5>
                                        </div>
                                        <div class="row p-1">
                                            <div class="col-6">
                                                <p style="font-size:18px">{{ posts[13] }}</p>
                                            </div>
                                            <div class="col-1"></div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <br></br>
                    {% if owner %}
                        <div class="row">
                            <div class="text-center">
                                <a href="{{ url_for('posts.edit_posts_by_id', post_id=posts[9]) }}" class="btn btn-primary">Edit Post</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <hr></hr>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

reviews/templates/user_db.html
{% extends "layout.html" %}
{% block content %}
<div style="background-color: #B83B5E; min-height:900px">
    <div class="container p-3" style="color:#F9ED69; width: 1400px">
        <div class="text-center">
            <h1>User Database</h1>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table" style="color:#4b6d7c">
                    <thead>
                        <tr>
                            <th>User ID</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Location</th>
                            <th>Post Count</th>
                            <th>User Information</th>
                            <th>User Posts</th>
                            <th>User Dashboard</th>
                            <th>User Role</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in profile_settings %}
                        <tr>
                            <th>{{ user[0] }}</th>
                            <th>{{ user[1] }}</th>
                            <th>{{ user[2] }}</th>
                            <th>{{ user[3] }}</th>
                            <th>{{ user[5] }}</th>
                            <th><a href="{{ url_for('privileges.user_profile', user_id=user[0]) }}" style="color:#F9ED69;">Information</a></th>
                            <th><a href="{{ url_for('privileges.user_posts', user_id=user[0]) }}" style="color:#F9ED69;">Posts</a></th>
                            <th><a href="{{ url_for('privileges.user_dashboard', user_id=user[0]) }}" style="color:#F9ED69;">Dashboard</a></th>
                            <th>{{ user[4] }}</th>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}